title: aitl-silicon-pathway
description: Educational project that explores the AITL control architecture
lang: en

url: "https://samizo-aitl.github.io"
baseurl: "/aitl-silicon-pathway"   # Project site. If publishing at root, set this to "".

theme: minima

markdown: kramdown
kramdown:
  input: GFM
